export const ERROR_MESSAGE = {
    CONTACT_FORM_ERROR: 'Failed to submit your request. Please try again in sometime',
    SURVEY_FORM_ERROR: 'Failed to submit your request. Please try again in sometime',
    TITLE_ERROR: "Title is required",
    NAME_ERROR: 'Name is mandatory',
    FIRST_NAME_ERROR: 'First name field is mandatory',
    LAST_NAME_ERROR: 'Last name field is mandatory',
    EMAIL_ERROR: 'Email ID field is mandatory',
    EMAIL_INVALID_ERROR: 'Enter valid Email ID',
    COUNTRY_ERROR: 'Country required',
    STATE_ERROR: 'State required',
    CITY_ERROR: 'City required',
    ZIP_ERROR: 'Zip Code required',
    PASSWORD_ERROR: 'Password is required',
    CONFIRM_PASSWORD_ERROR: 'Confirm Password is required',
    AREA_OF_INTEREST_ERROR: 'Area of interest is required',
    MOBILE_ERROR: 'Mobile Number field is mandatory',
    MOBILE_INVALID_ERROR: 'Enter correct Mobile Number',
    MESSAGE_ERROR: 'Message is required',
    DOB_ERROR: 'Date of Birth field is mandatory',
    GENDER_ERROR: 'Gender field is mandatory',
    INTERESTED_IN_ERROR: 'Select minimum one option',
    EXPERTISE_ERROR: 'Enter minimum one expertise',
    PREFERRED_LANGUAGES_ERROR: 'Preferred Language required',
    LANGUAGES_KNOWN_ERROR: 'Select minimum one language',
    CURRENT_WORKPLACE_ERROR: 'Current Workplace required',
    EXPERIENCE_ERROR: 'Experience is required',
    SPECIALIZATION_ERROR: 'Specialization is required',
    QUALIFICATION_ERROR: 'Qualification is required',
    PASSING_YEAR_ERROR: 'Year of passing required',
}
export const SUCCESS_MESSAGE = {
    SURVEY_FORM_SUCCESS: 'Survey form submitted successfully',
}